### ISSUE TITLE
Save and close button in settings doesn't work

### ISSUE THREAD

**Issue by FreakyGamingStudios** [Twingamerdudes/Chaos-Mod#2]
Trying to disable enemy spawning but can't since the save and close button doesn't work.

The close without saving button works flawlessly though.

**Comment by blanana** [comment]
It could be that your Chaos Mod Save file is broken from the update.
This happened to me on a different project once.
We changed a the Save file a lot so it could be case.
If the file is broken, the Cast after the file load will fail and nothing happens.
Try deleting your Chaos Mod save file and opening the Mod again.
It should be under "AppData\Local\fnaf9\Saved\SaveGames" and the file should be called "Agony.sav"
