### ISSUE TITLE
Dance Break Event can doxx people.

### ISSUE THREAD

**Issue by Snakeybus** [Twingamerdudes/Chaos-Mod#4]
People who have webcams and are faceless youtubers can be doxxed live on stream if they play through the mod blind. Please remove the camera access, or remove the Dance Break Event accordingly

**Comment by Twingamerdudes** [comment]
Good catch! I'm going to make it so this event is disabled under streamer mode like it should've been. Tell me if there are any issues with this way to implement the event

**Comment by Twingamerdudes** [comment]
Actually, the dance break event is already blacklisted in streamer mode, there is one more event that isn't blacklisted that could also dox ppl, so that's been added to the blacklist too
